### ISSUE TITLE
本地调式报错

### ISSUE THREAD

**Issue by super456** [dmego/together#3]
![01](https://user-images.githubusercontent.com/22334247/39093332-78dbb8d6-4650-11e8-838e-7b235cc7973b.png)
微信开发工具版本：v1.02.1804120
测试过源码也是卡在这个地方一直连不上
还有一个问题是：每次点开反馈意见都会报这个错，那时候用户名信息也是为空的，很奇怪
![02](https://user-images.githubusercontent.com/22334247/39093351-d62088c8-4650-11e8-89bb-a5aa72e7782d.png)
请教一下，谢谢

**Comment by dmego** [comment]
更新一下sdk，现在bmob的sdk应该和我当时开发的时候改变了许多地方，可以参考着bmob的开发文档看看
